### ISSUE TITLE
What's the right HTTP semantics to trigger a fetch?

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#573]
Currently, you can trigger a fetch of an existing repo by sending an empty payload to:

    POST /repos/:repoId

The semantics of this are confusing, I think.

1. It sits very close to the endpoint for creating/updating a repo (`PUT /repos/:repoId`).
2. My understanding of the [RFC](https://tools.ietf.org/html/rfc7231#section-4.3.3) is that `POST` is meant to be used for adding items to a collection, not sending data to a specific existing resource/item.

So what would be better semantics for triggering a `git fetch` on the underlying local clone? I feel like `POST /repos/:repoId/fetches` is not very nice, as there isn't really such a concept as a collection of fetches in git. Maybe just POSTing an empty payload to `repos/:repoId/commits` would be better?

**Comment by jbpros** [comment]
`POST /repos/:repoId` does not look right, indeed. It seems to signify a repo is being created and added to the collection of repos, it says nothing about fetching and updating from a remote.

I think `POST /repos/:repoId/fetches` makes sense. I wonder if your discomfort with this is due to the lack of a concrete "fetch" model in the code? If that's the case, remember that a resource is not the necessarily a (domain) model, as [outlined](https://tools.ietf.org/html/rfc7231#page-7) in the RFC:

> HTTP does not limit the nature of a resource; it merely defines an interface that might be used to interact with resources.

With that in mind, it feels absolutely right to "create a new *fetch*", a fetch which is a sub-resource of a repo and part of a set (collection) of past and future fetches. In a CQRS paradigm, a resource could be a command! The server could return a `201 Created` with a UID that can be used to track the outcome of that command. I can also easily see how that "fetch" resource could in fact be mapped to an actual model (that could track its result, date, owner, etc.)!

Does it make sense?

**Comment by mattwynne** [comment]
OK, so we need to move the existing fetch endpoint.

To do:

- [ ] duplicate tests and create a new endpoint at `/repos/:repoId/fetches`
- [ ] change acceptance tests to use the new endpoint
- [ ] check gherkin-editor and cucumber-studio for any calls to the old endpoint (I think there are none)
- [ ] remove the old endpoint
- [ ] add hypermedia links to new endpoint
- [ ] change the acceptance tests to walk the hypermedia link headers to the right URL

**Comment by mattwynne** [comment]
OK the main part of this is done. I think the hypermedia links should be done as a separate ticket.
